# NumPy Tutorial

**Goal**: Master NumPy fundamentals

## Table of Contents

1. [Introduction to NumPy](#1-introduction-to-numpy)
2. [NumPy Arrays (ndarrays)](#2-numpy-arrays-ndarrays)
3. [Array Creation Methods](#3-array-creation-methods)
4. [Array Attributes and Data Types](#4-array-attributes-and-data-types)
5. [Array Indexing and Slicing](#5-array-indexing-and-slicing)
6. [Array Reshaping and Manipulation](#6-array-reshaping-and-manipulation)
7. [Broadcasting](#7-broadcasting)
8. [Mathematical Operations](#8-mathematical-operations)
9. [Linear Algebra Operations](#9-linear-algebra-operations)
10. [Random Number Generation](#10-random-number-generation)
11. [Advanced Indexing](#11-advanced-indexing)
12. [Aggregation and Statistics](#12-aggregation-and-statistics)
13. [Stacking and Concatenation](#13-stacking-and-concatenation)
14. [NumPy to PyTorch Bridge](#14-numpy-to-pytorch-bridge)

---


## 1. Introduction to NumPy

**NumPy** (Numerical Python) is the foundational library for numerical computing in Python. It provides:

- Fast, efficient multi-dimensional array objects
- Broadcasting capabilities for element-wise operations
- Mathematical functions for arrays
- Linear algebra, random number generation, and more

### Why NumPy for PyTorch?

PyTorch tensors are heavily inspired by NumPy arrays. Understanding NumPy:

- Makes learning PyTorch intuitive
- Enables easy data preparation
- Provides a mental model for tensor operations

```mermaid
graph LR
    A[Python Lists] --> B[NumPy Arrays]
    B --> C[PyTorch Tensors]
    B --> D[Deep Learning]
    C --> D
    style B fill:#eee,stroke:#333,stroke-width:2px
    style C fill:#aaa,stroke:#333,stroke-width:2px
```


In [1]:
# Import NumPy (standard convention is to use 'np' alias)
import numpy as np

# Check NumPy version
print(f"NumPy version: {np.__version__}")

NumPy version: 2.4.2


## 2. NumPy Arrays (ndarrays)

The core of NumPy is the **ndarray** (n-dimensional array) object.

### Key Characteristics:

- **Homogeneous**: All elements have the same data type
- **Fixed size**: Size is determined at creation
- **Multi-dimensional**: Can have any number of dimensions
- **Efficient**: Stored in contiguous memory blocks

```mermaid
graph TD
    A[ndarray] --> B[1D Array - Vector]
    A --> C[2D Array - Matrix]
    A --> D[3D Array - Tensor]
    A --> E[nD Array - Higher Dimensions]
    B --> F[Shape: n,]
    C --> G[Shape: m, n]
    D --> H[Shape: d, m, n]
```


In [2]:
# Creating arrays from Python lists
# 1D array (vector)
arr_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:")
print(arr_1d)
print(f"Shape: {arr_1d.shape}")
print(f"Dimensions: {arr_1d.ndim}\n")

# 2D array (matrix)
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6]])
print("2D Array:")
print(arr_2d)
print(f"Shape: {arr_2d.shape}")
print(f"Dimensions: {arr_2d.ndim}\n")

# 3D array (tensor)
arr_3d = np.array([[[1, 2], [3, 4]],
                   [[5, 6], [7, 8]]])
print("3D Array:")
print(arr_3d)
print(f"Shape: {arr_3d.shape}")
print(f"Dimensions: {arr_3d.ndim}")

1D Array:
[1 2 3 4 5]
Shape: (5,)
Dimensions: 1

2D Array:
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Dimensions: 2

3D Array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Shape: (2, 2, 2)
Dimensions: 3


## 3. Array Creation Methods

NumPy provides many functions to create arrays efficiently.

```mermaid
graph TD
    A[Array Creation] --> B[From Data]
    A --> C[Initialized Arrays]
    A --> D[Sequences]
    A --> E[Random Arrays]
    B --> B1[np.array]
    C --> C1[np.zeros]
    C --> C2[np.ones]
    C --> C3[np.empty]
    C --> C4[np.full]
    D --> D1[np.arange]
    D --> D2[np.linspace]
    E --> E1[np.random.*]
```


### 3.1 np.zeros()

Creates an array filled with zeros.

**Syntax**: `np.zeros(shape, dtype=float, order='C')`

**Parameters**:

- `shape`: int or tuple of ints - Shape of the array
- `dtype`: data type (optional) - Default is float64
- `order`: 'C' (row-major) or 'F' (column-major) - Memory layout


In [3]:
# Create 1D array of zeros
zeros_1d = np.zeros(5)
print("1D zeros:")
print(zeros_1d)

# Create 2D array of zeros
zeros_2d = np.zeros((3, 4))
print("\n2D zeros:")
print(zeros_2d)

# Create with specific data type
zeros_int = np.zeros((2, 3), dtype=int)
print("\n2D zeros (integer):")
print(zeros_int)

1D zeros:
[0. 0. 0. 0. 0.]

2D zeros:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

2D zeros (integer):
[[0 0 0]
 [0 0 0]]


### 3.2 np.ones()

Creates an array filled with ones.

**Syntax**: `np.ones(shape, dtype=float, order='C')`

**Parameters**: Same as np.zeros()


In [4]:
# Create 1D array of ones
ones_1d = np.ones(4)
print("1D ones:")
print(ones_1d)

# Create 3D array of ones
ones_3d = np.ones((2, 3, 4))
print("\n3D ones shape:", ones_3d.shape)
print(ones_3d)

1D ones:
[1. 1. 1. 1.]

3D ones shape: (2, 3, 4)
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


#### Understanding the `order` Parameter

The `order` parameter controls how multi-dimensional arrays are stored in computer memory. This is a fundamental concept that affects performance and compatibility with other libraries.

**Two memory layouts**:

1. **'C' order (Row-Major)** - DEFAULT
   - Elements of each row stored contiguously in memory
   - Used by C, C++, Python, NumPy (default)
   - Last index changes fastest when traversing memory

2. **'F' order (Column-Major)**
   - Elements of each column stored contiguously in memory
   - Used by Fortran, MATLAB, R
   - First index changes fastest when traversing memory

**Visual Example - 2×3 Array:**

```
Array visualization:
[[1, 2, 3],
 [4, 5, 6]]

'C' order in memory: [1, 2, 3, 4, 5, 6]  ← row-by-row
'F' order in memory: [1, 4, 2, 5, 3, 6]  ← column-by-column
```

**When does it matter?**

- 🚀 **Performance**: Operations along contiguous memory are faster
- 🔗 **Interoperability**: Passing arrays to C/Fortran libraries
- 💾 **Cache efficiency**: Better CPU cache utilization
- ⚠️ **Usually**: You can ignore this and use the default 'C' order


#### Practical Guidance on `order`

**When to use 'C' order (default):**

- ✅ 99% of the time - it's the default for good reason
- ✅ Working with Python, C, C++ libraries
- ✅ Deep learning with PyTorch, TensorFlow
- ✅ When processing data row-by-row
- ✅ Image data (rows are typically contiguous)

**When to use 'F' order:**

- 🔧 Interfacing with Fortran/MATLAB code
- 🔧 When you need column-wise operations to be fastest
- 🔧 Scientific computing libraries that expect F-order
- 🔧 Linear algebra operations (some BLAS/LAPACK routines prefer F-order)

**Performance Example:**

```python
# C-order is faster for row operations
arr_c = np.zeros((1000, 1000), order='C')
# This is fast: np.sum(arr_c, axis=1)  # sum rows

# F-order is faster for column operations
arr_f = np.zeros((1000, 1000), order='F')
# This is fast: np.sum(arr_f, axis=0)  # sum columns
```

**Key Takeaway:**

> Unless you have a specific reason to use 'F' order, stick with the default 'C' order. NumPy is optimized for C-order, and it's what PyTorch expects.


### 3.3 np.full()

Creates an array filled with a specific value.

**Syntax**: `np.full(shape, fill_value, dtype=None, order='C')`

**Parameters**:

- `shape`: int or tuple of ints - Shape of the array
- `fill_value`: scalar - The value to fill the array with
- `dtype`: data type (optional) - Inferred from fill_value if not specified
- `order`: 'C' or 'F' - Memory layout


In [8]:
# Create array filled with 7
sevens = np.full((3, 3), 7)
print("Array filled with 7:")
print(sevens)

# Create array filled with pi
pis = np.full((2, 4), np.pi)
print("\nArray filled with π:")
print(pis)

Array filled with 7:
[[7 7 7]
 [7 7 7]
 [7 7 7]]

Array filled with π:
[[3.14159265 3.14159265 3.14159265 3.14159265]
 [3.14159265 3.14159265 3.14159265 3.14159265]]


### 3.4 np.eye() and np.identity()

Create identity matrices (diagonal of ones).

**Syntax**:

- `np.eye(N, M=None, k=0, dtype=float)`
- `np.identity(n, dtype=float)`

**Parameters (np.eye)**:

- `N`: int - Number of rows
- `M`: int (optional) - Number of columns (defaults to N)
- `k`: int - Index of diagonal (0=main diagonal, positive=upper, negative=lower)
- `dtype`: data type


In [9]:
# Identity matrix 3x3
identity = np.eye(3)
print("3x3 Identity matrix:")
print(identity)

# Non-square with diagonal offset
eye_offset = np.eye(4, 5, k=1)
print("\n4x5 with diagonal offset +1:")
print(eye_offset)

3x3 Identity matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

4x5 with diagonal offset +1:
[[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


### 3.5 np.arange()

Creates an array with evenly spaced values within an interval.

**Syntax**: `np.arange(start, stop, step, dtype=None)`

**Parameters**:

- `start`: number (optional) - Start of interval (default 0)
- `stop`: number - End of interval (exclusive)
- `step`: number (optional) - Spacing between values (default 1)
- `dtype`: data type (optional)


In [10]:
# Basic range
range_basic = np.arange(10)
print("Range 0 to 9:")
print(range_basic)

# With start and stop
range_start_stop = np.arange(5, 15)
print("\nRange 5 to 14:")
print(range_start_stop)

# With step
range_step = np.arange(0, 20, 3)
print("\nRange 0 to 20 with step 3:")
print(range_step)

# Float step
range_float = np.arange(0, 1, 0.1)
print("\nRange 0 to 1 with step 0.1:")
print(range_float)

Range 0 to 9:
[0 1 2 3 4 5 6 7 8 9]

Range 5 to 14:
[ 5  6  7  8  9 10 11 12 13 14]

Range 0 to 20 with step 3:
[ 0  3  6  9 12 15 18]

Range 0 to 1 with step 0.1:
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


### 3.6 np.linspace()

Creates an array with evenly spaced values over a specified interval.

**Syntax**: `np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)`

**Parameters**:

- `start`: number - Start of interval
- `stop`: number - End of interval
- `num`: int - Number of samples to generate (default 50)
- `endpoint`: bool - Include stop value (default True)
- `retstep`: bool - Return step size (default False)
- `dtype`: data type (optional)

**Difference from arange**: linspace specifies number of points, arange specifies step size


In [11]:
# 10 evenly spaced points between 0 and 1
linspace_basic = np.linspace(0, 1, 10)
print("10 points from 0 to 1:")
print(linspace_basic)

# Without endpoint
linspace_no_end = np.linspace(0, 1, 5, endpoint=False)
print("\n5 points from 0 to 1 (excluding 1):")
print(linspace_no_end)

# Return step size
linspace_step, step = np.linspace(0, 10, 5, retstep=True)
print("\n5 points from 0 to 10:")
print(linspace_step)
print(f"Step size: {step}")

10 points from 0 to 1:
[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]

5 points from 0 to 1 (excluding 1):
[0.  0.2 0.4 0.6 0.8]

5 points from 0 to 10:
[ 0.   2.5  5.   7.5 10. ]
Step size: 2.5


## 4. Array Attributes and Data Types

Every NumPy array has important attributes that describe its structure and content.

```mermaid
graph LR
    A[NumPy Array] --> B[shape]
    A --> C[ndim]
    A --> D[size]
    A --> E[dtype]
    A --> F[itemsize]
    A --> G[nbytes]
    B --> B1[Tuple of dimensions]
    C --> C1[Number of dimensions]
    D --> D1[Total elements]
    E --> E1[Data type]
    F --> F1[Bytes per element]
    G --> G1[Total bytes]
```


In [12]:
# Create sample array
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

print("Array:")
print(arr)
print(f"\nshape: {arr.shape}        # Tuple of array dimensions (3 rows, 4 columns)")
print(f"ndim: {arr.ndim}          # Number of dimensions (2D array)")
print(f"size: {arr.size}         # Total number of elements (3 × 4 = 12)")
print(f"dtype: {arr.dtype}       # Data type of elements")
print(f"itemsize: {arr.itemsize}     # Size of each element in bytes")
print(f"nbytes: {arr.nbytes}       # Total bytes consumed (12 elements × 8 bytes)")

Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

shape: (3, 4)        # Tuple of array dimensions (3 rows, 4 columns)
ndim: 2          # Number of dimensions (2D array)
size: 12         # Total number of elements (3 × 4 = 12)
dtype: int64       # Data type of elements
itemsize: 8     # Size of each element in bytes
nbytes: 96       # Total bytes consumed (12 elements × 8 bytes)


### 4.1 Data Types (dtype)

NumPy supports many data types, crucial for memory efficiency and precision.

**Common dtypes**:

- **Integers**: `int8`, `int16`, `int32`, `int64`, `uint8`, `uint16`, `uint32`, `uint64`
- **Floats**: `float16`, `float32`, `float64`, `float128`
- **Complex**: `complex64`, `complex128`
- **Boolean**: `bool`
- **Strings**: `str_`, `unicode_`


In [14]:
# Integer array
int_arr = np.array([1, 2, 3], dtype=np.int32)
print(f"Integer array dtype: {int_arr.dtype}")

# Float array
float_arr = np.array([1.0, 2.0, 3.0], dtype=np.float32)
print(f"Float array dtype: {float_arr.dtype}")

# Boolean array
bool_arr = np.array([True, False, True], dtype=bool)
print(f"Boolean array dtype: {bool_arr.dtype}")

# Type conversion (astype)
original = np.array([1.7, 2.3, 3.9])
converted = original.astype(int)
print(f"\nOriginal (float): {original}")
print(f"Converted (int): {converted}")

Integer array dtype: int32
Float array dtype: float32
Boolean array dtype: bool

Original (float): [1.7 2.3 3.9]
Converted (int): [1 2 3]


## 5. Array Indexing and Slicing

Accessing and modifying array elements is fundamental for data manipulation.

```mermaid
graph TD
    A[Array Access] --> B[Single Element]
    A --> C[Slicing]
    A --> D[Boolean Indexing]
    A --> E[Fancy Indexing]
    B --> B1["arr#91;i#93; or arr#91;i,j#93;"]
    C --> C1["arr#91;start:stop:step#93;"]
    D --> D1["arr#91;condition#93;"]
    E --> E1["arr#91;#91;indices#93;#93;"]

    style A fill:#e1f5ff,stroke:#333,stroke-width:2px
    style B fill:#fff4e6,stroke:#333
    style C fill:#fff4e6,stroke:#333
    style D fill:#fff4e6,stroke:#333
    style E fill:#fff4e6,stroke:#333
    style B1 fill:#f0f0f0,stroke:#666
    style C1 fill:#f0f0f0,stroke:#666
    style D1 fill:#f0f0f0,stroke:#666
    style E1 fill:#f0f0f0,stroke:#666
```


### 5.1 Basic Indexing (1D Arrays)


In [ ]:
arr_1d = np.array([10, 20, 30, 40, 50, 60, 70])
print("Original array:", arr_1d)

# Single element access
print(f"\nFirst element (index 0): {arr_1d[0]}")
print(f"Third element (index 2): {arr_1d[2]}")

# Negative indexing (from the end)
print(f"Last element (index -1): {arr_1d[-1]}")
print(f"Second to last (index -2): {arr_1d[-2]}")

# Modifying elements
arr_1d[0] = 99
print(f"\nAfter modifying first element: {arr_1d}")

### 5.2 Slicing (1D Arrays)

**Syntax**: `arr[start:stop:step]`

**Parameters**:

- `start`: Starting index (inclusive, default 0)
- `stop`: Ending index (exclusive)
- `step`: Step size (default 1)


In [ ]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print("Original array:", arr)

# Basic slicing
print(f"\narr[2:5]: {arr[2:5]}")        # Elements at index 2, 3, 4
print(f"arr[:4]: {arr[:4]}")            # First 4 elements
print(f"arr[6:]: {arr[6:]}")            # From index 6 to end
print(f"arr[:]: {arr[:]}")              # All elements (copy)

# Step parameter
print(f"\narr[::2]: {arr[::2]}")        # Every other element
print(f"arr[1::2]: {arr[1::2]}")        # Every other element starting from index 1
print(f"arr[::-1]: {arr[::-1]}")        # Reverse the array
print(f"arr[7:2:-1]: {arr[7:2:-1]}")    # From index 7 to 3 (reverse)

### 5.3 Multi-dimensional Indexing


In [ ]:
arr_2d = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])
print("2D Array:")
print(arr_2d)

# Single element access
print(f"\nElement at row 0, col 2: {arr_2d[0, 2]}")    # 3
print(f"Element at row 2, col 1: {arr_2d[2, 1]}")      # 10

# Row access
print(f"\nFirst row: {arr_2d[0]}")       # or arr_2d[0, :]
print(f"Last row: {arr_2d[-1]}")

# Column access
print(f"\nFirst column: {arr_2d[:, 0]}")
print(f"Third column: {arr_2d[:, 2]}")

# Subarray slicing
print(f"\nFirst 2 rows, first 3 cols:")
print(arr_2d[:2, :3])

print(f"\nAll rows, columns 1-2:")
print(arr_2d[:, 1:3])

### 5.4 Boolean Indexing

Select elements based on conditions (very powerful for filtering!).


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Create boolean mask
mask = arr > 5
print("Array:", arr)
print("Mask (arr > 5):", mask)
print("Elements > 5:", arr[mask])

# Direct filtering
print(f"\nEven numbers: {arr[arr % 2 == 0]}")
print(f"Numbers between 3 and 7: {arr[(arr >= 3) & (arr <= 7)]}")

# Modifying with boolean indexing
arr_copy = arr.copy()
arr_copy[arr_copy > 5] = 0
print(f"\nSet elements > 5 to 0: {arr_copy}")

### 5.5 Views vs Copies

**Important concept**: Slicing creates views (references), not copies!

```mermaid
graph LR
    A[Original Array] --> B[Slice/View]
    A --> C[Copy]
    B -.->|Shares memory| A
    C -->|Independent memory| D[New Array]
    style B fill:#bbbbbb,stroke:#333
    style C fill:#aaaaaa,stroke:#333
```


In [ ]:
# View example (default behavior)
original = np.array([1, 2, 3, 4, 5])
view = original[1:4]  # This is a view

print("Original:", original)
print("View:", view)

# Modify the view
view[0] = 99
print("\nAfter modifying view:")
print("Original:", original)  # Original is also changed!
print("View:", view)

# Copy example
original = np.array([1, 2, 3, 4, 5])
copy = original[1:4].copy()  # Explicit copy

print("\n--- Copy Example ---")
print("Original:", original)
print("Copy:", copy)

copy[0] = 99
print("\nAfter modifying copy:")
print("Original:", original)  # Original is NOT changed
print("Copy:", copy)

## 6. Array Reshaping and Manipulation

Changing array shapes is crucial for deep learning (e.g., preparing batches).

```mermaid
graph TD
    A[Shape Operations] --> B[reshape]
    A --> C[ravel/flatten]
    A --> D[transpose]
    A --> E[expand_dims]
    A --> F[squeeze]
    B --> B1[Change shape, same data]
    C --> C1[Convert to 1D]
    D --> D1[Swap axes]
    E --> E1[Add dimension]
    F --> F1[Remove singleton dims]
```


### 6.1 reshape()

**Syntax**: `arr.reshape(new_shape)` or `np.reshape(arr, new_shape)`

**Parameters**:

- `new_shape`: int or tuple - New shape (must be compatible with array size)
- Can use -1 for one dimension to auto-calculate

**Note**: Returns a view if possible, otherwise a copy


In [ ]:
# Create 1D array with 12 elements
arr = np.arange(12)
print("Original 1D array:")
print(arr)
print(f"Shape: {arr.shape}")

# Reshape to 2D
arr_2d = arr.reshape(3, 4)
print("\nReshaped to 3×4:")
print(arr_2d)
print(f"Shape: {arr_2d.shape}")

# Reshape to 3D
arr_3d = arr.reshape(2, 2, 3)
print("\nReshaped to 2×2×3:")
print(arr_3d)
print(f"Shape: {arr_3d.shape}")

# Auto-calculate dimension with -1
arr_auto = arr.reshape(4, -1)  # -1 means "figure out this dimension"
print("\nReshaped to 4×? (auto-calculated as 4×3):")
print(arr_auto)
print(f"Shape: {arr_auto.shape}")

### 6.2 ravel() and flatten()

Convert multi-dimensional array to 1D.

**Difference**:

- `ravel()`: Returns a view if possible (faster)
- `flatten()`: Always returns a copy


In [ ]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6]])
print("Original 2D array:")
print(arr_2d)

# ravel - returns view
raveled = arr_2d.ravel()
print("\nRaveled (view):")
print(raveled)

# flatten - returns copy
flattened = arr_2d.flatten()
print("\nFlattened (copy):")
print(flattened)

# Test view vs copy
raveled[0] = 99
print("\nAfter modifying raveled[0]:")
print("Original array:", arr_2d)  # Changed!

flattened[0] = 88
print("\nAfter modifying flattened[0]:")
print("Original array:", arr_2d)  # Not changed

### 6.3 transpose() and T

**Syntax**: `arr.transpose()` or `arr.T`

For 2D: Swaps rows and columns  
For nD: Can specify axis permutation

**Parameters (transpose)**:

- `axes`: tuple (optional) - Permutation of axes


In [ ]:
# 2D transpose
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print("Original (2×3):")
print(arr)
print(f"Shape: {arr.shape}")

transposed = arr.T
print("\nTransposed (3×2):")
print(transposed)
print(f"Shape: {transposed.shape}")

# 3D transpose with axis permutation
arr_3d = np.arange(24).reshape(2, 3, 4)
print("\n3D array shape:", arr_3d.shape)  # (2, 3, 4)

# Permute axes: (0, 1, 2) -> (2, 0, 1)
permuted = arr_3d.transpose(2, 0, 1)
print("After transpose(2,0,1):", permuted.shape)  # (4, 2, 3)

### 6.4 expand_dims() and squeeze()

#### expand_dims() - Add a New Dimension

Add a new axis (dimension of size 1) at a specified position.

**Syntax**: `np.expand_dims(arr, axis)`

**Parameters**:

- `arr`: Input array
- `axis`: int - Position where new axis is placed
  - Positive: Insert before that position (0 = first, 1 = second, etc.)
  - Negative: Count from the end (-1 = last position)

**How axis works here:**

- `axis=0`: Insert new dimension at the beginning → shape `(n,)` becomes `(1, n)`
- `axis=1`: Insert new dimension at position 1 → shape `(n,)` becomes `(n, 1)`
- `axis=-1`: Insert new dimension at the end → shape `(n,)` becomes `(n, 1)`

**Use case**: Preparing data for broadcasting or matching expected dimensions (e.g., adding batch dimension)

---

#### squeeze() - Remove Singleton Dimensions

Remove axes of length 1 from the shape.

**Syntax**: `np.squeeze(arr, axis=None)`

**Parameters**:

- `arr`: Input array
- `axis`: None or int/tuple - If None, remove all singleton dimensions; if specified, only remove that dimension if it's size 1

**Use case**: Removing unnecessary dimensions after operations


In [ ]:
# expand_dims example
arr = np.array([1, 2, 3, 4])
print("Original array shape:", arr.shape)  # (4,)

# Add axis at position 0
expanded_0 = np.expand_dims(arr, axis=0)
print("\nExpanded at axis 0:", expanded_0.shape)  # (1, 4)
print(expanded_0)

# Add axis at position 1
expanded_1 = np.expand_dims(arr, axis=1)
print("\nExpanded at axis 1:", expanded_1.shape)  # (4, 1)
print(expanded_1)

# squeeze example
arr_with_singleton = np.array([[[1, 2, 3]]])  # Shape: (1, 1, 3)
print("\nArray with singleton dims:", arr_with_singleton.shape)

squeezed = np.squeeze(arr_with_singleton)
print("After squeeze:", squeezed.shape)  # (3,)
print(squeezed)

## 7. Broadcasting

**Broadcasting** allows NumPy to perform operations on arrays of different shapes.

### Broadcasting Rules:

1. If arrays have different ranks, prepend 1s to the smaller rank array
2. Arrays are compatible if dimensions are equal OR one is 1
3. After broadcasting, each array behaves as if it had shape equal to element-wise max

```mermaid
graph TD
    A[Broadcasting] --> B[Scalar + Array]
    A --> C[1D + 2D]
    A --> D[Compatible Shapes]
    B --> B1["(1,) + (n,) = (n,)"]
    C --> C1["(n,) + (m,n) = (m,n)"]
    D --> D1["(m,1) + (1,n) = (m,n)"]
```

```mermaid
flowchart LR
    subgraph Example1["Example: Scalar + Matrix"]
        A1[5] -->|broadcast to| A2["[5 5 5]\n[5 5 5]"]
        A3["[1 2 3]\n[4 5 6]"] --> A4[+]
        A2 --> A4
        A4 --> A5["[6 7 8]\n[9 10 11]"]
    end
```


In [ ]:
# Example 1: Scalar + Array
arr = np.array([1, 2, 3, 4])
result = arr + 10
print("Array + Scalar:")
print(f"{arr} + 10 = {result}")

# Example 2: 1D + 2D (row-wise operation)
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
row_vec = np.array([10, 20, 30])

print("\nMatrix + Row Vector:")
print("Matrix:")
print(matrix)
print(f"\nRow vector: {row_vec}")
print("\nResult:")
print(matrix + row_vec)

# Example 3: Column vector + Row vector = Matrix
col_vec = np.array([[1], [2], [3]])  # Shape: (3, 1)
row_vec = np.array([[10, 20, 30]])    # Shape: (1, 3)

print("\nColumn vector (3×1):")
print(col_vec)
print("\nRow vector (1×3):")
print(row_vec)
print("\nBroadcasted addition (3×3):")
print(col_vec + row_vec)

### Broadcasting Shape Compatibility Examples


In [ ]:
# Compatible shapes
print("Compatible Broadcasting Examples:")
print("="*50)

# Shape (4,) + Shape (4,) = Shape (4,)
a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])
print(f"(4,) + (4,) = {a + b}")

# Shape (3, 4) + Shape (4,) = Shape (3, 4)
a = np.ones((3, 4))
b = np.array([1, 2, 3, 4])
print(f"\n(3,4) + (4,) shape: {(a + b).shape}")

# Shape (3, 1) + Shape (1, 4) = Shape (3, 4)
a = np.ones((3, 1))
b = np.ones((1, 4))
print(f"(3,1) + (1,4) shape: {(a + b).shape}")

# Incompatible example (will raise error)
print("\n" + "="*50)
print("Incompatible Broadcasting Example:")
try:
    a = np.ones((3, 4))
    b = np.ones((3, 5))
    result = a + b
except ValueError as e:
    print(f"Error: {e}")

## 8. Mathematical Operations

NumPy provides element-wise operations and universal functions (ufuncs).

```mermaid
graph TD
    A[Math Operations] --> B[Arithmetic]
    A --> C[Comparison]
    A --> D[Trigonometric]
    A --> E[Exponential/Log]
    A --> F[Rounding]
    B --> B1["+, -, *, /, //, %, **"]
    C --> C1["<, >, ==, !=, <=, >="]
    D --> D1["sin, cos, tan, etc."]
    E --> E1["exp, log, log10, etc."]
    F --> F1["round, floor, ceil, etc."]
```


### 8.1 Arithmetic Operations

Element-wise operations between arrays or array and scalar.


In [ ]:
a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])

print("a =", a)
print("b =", b)
print()

# Basic arithmetic
print(f"Addition: a + b = {a + b}")
print(f"Subtraction: a - b = {a - b}")
print(f"Multiplication: a * b = {a * b}")
print(f"Division: b / a = {b / a}")
print(f"Floor division: b // a = {b // a}")
print(f"Modulo: b % a = {b % a}")
print(f"Power: a ** 2 = {a ** 2}")

# Function form (equivalent)
print(f"\nUsing functions:")
print(f"np.add(a, b) = {np.add(a, b)}")
print(f"np.multiply(a, b) = {np.multiply(a, b)}")

### 8.2 Comparison Operations

Return boolean arrays.


In [ ]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([5, 4, 3, 2, 1])

print("a =", a)
print("b =", b)
print()

print(f"a == b: {a == b}")
print(f"a > b: {a > b}")
print(f"a < b: {a < b}")
print(f"a >= 3: {a >= 3}")

# Useful for filtering
print(f"\nElements where a > 2: {a[a > 2]}")

### 8.3 Mathematical Functions

NumPy provides many mathematical functions.


In [ ]:
arr = np.array([1, 4, 9, 16, 25])

# Square root
print(f"Square root: {np.sqrt(arr)}")

# Exponential and logarithm
arr2 = np.array([1, 2, 3])
print(f"\nExponential e^x: {np.exp(arr2)}")
print(f"Natural log: {np.log(arr2)}")
print(f"Log base 10: {np.log10(arr2)}")
print(f"Log base 2: {np.log2(arr2)}")

# Trigonometric
angles = np.array([0, np.pi/6, np.pi/4, np.pi/3, np.pi/2])
print(f"\nSine: {np.sin(angles)}")
print(f"Cosine: {np.cos(angles)}")

# Rounding
arr3 = np.array([1.2, 2.5, 3.7, 4.9])
print(f"\nOriginal: {arr3}")
print(f"Round: {np.round(arr3)}")
print(f"Floor: {np.floor(arr3)}")
print(f"Ceil: {np.ceil(arr3)}")

### 8.4 Clipping and Absolute Values


In [ ]:
arr = np.array([-5, -2, 0, 3, 8, 15])

# Absolute value
print(f"Original: {arr}")
print(f"Absolute: {np.abs(arr)}")

# Clip values to range
# np.clip(arr, min, max) - limit values to [min, max]
clipped = np.clip(arr, -2, 5)
print(f"\nClipped to [-2, 5]: {clipped}")

## 9. Linear Algebra Operations

Essential for deep learning! PyTorch heavily uses these concepts.

```mermaid
graph TD
    A[Linear Algebra] --> B[Matrix Multiplication]
    A --> C[Dot Product]
    A --> D[Matrix Properties]
    A --> E[Decompositions]
    B --> B1["np.matmul, @"]
    C --> C1[np.dot]
    D --> D1["det, inv, trace"]
    E --> E1["SVD, eigenvalues"]
```


### 9.1 Dot Product and Matrix Multiplication

**np.dot()**: Dot product of two arrays

- 1D arrays: Inner product (sum of element-wise multiplication)
- 2D arrays: Matrix multiplication

**np.matmul()** or **@**: Matrix multiplication (preferred for 2D+)

```mermaid
flowchart LR
    subgraph Multiplication["Matrix Multiplication"]
        A["Matrix A\n(m × n)"] --> C["@"]
        B["Matrix B\n(n × p)"] --> C
        C --> D["Result\n(m × p)"]
    end
```


In [ ]:
# Dot product of 1D arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
dot_product = np.dot(a, b)  # 1*4 + 2*5 + 3*6 = 32
print(f"Dot product of {a} and {b}: {dot_product}")

# Matrix multiplication
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])

print("\nMatrix A (2×2):")
print(A)
print("\nMatrix B (2×2):")
print(B)

# Three equivalent ways
result1 = np.dot(A, B)
result2 = np.matmul(A, B)
result3 = A @ B  # Preferred modern syntax

print("\nA @ B:")
print(result3)

# Matrix-vector multiplication
A = np.array([[1, 2, 3],
              [4, 5, 6]])
v = np.array([1, 0, 1])

result = A @ v
print(f"\nMatrix (2×3) @ Vector (3,):")
print(f"Result shape: {result.shape}")
print(result)

### 9.2 Matrix Operations

Important matrix operations from `np.linalg` module.


In [ ]:
# Create a square matrix
A = np.array([[1, 2],
              [3, 4]])

print("Matrix A:")
print(A)

# Transpose
print("\nTranspose A.T:")
print(A.T)

# Determinant
det_A = np.linalg.det(A)
print(f"\nDeterminant: {det_A}")

# Inverse (if determinant != 0)
inv_A = np.linalg.inv(A)
print("\nInverse:")
print(inv_A)

# Verify: A @ inv(A) = Identity
print("\nA @ inv(A):")
print(A @ inv_A)

# Trace (sum of diagonal elements)
trace_A = np.trace(A)
print(f"\nTrace: {trace_A}")

### 9.3 Eigenvalues and Eigenvectors


In [ ]:
# Symmetric matrix for clearer eigenvalues
A = np.array([[4, 2],
              [2, 3]])

print("Matrix A:")
print(A)

# Compute eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)

print(f"\nEigenvalues: {eigenvalues}")
print("\nEigenvectors:")
print(eigenvectors)

# Verify: A @ v = λ @ v
v1 = eigenvectors[:, 0]
lambda1 = eigenvalues[0]
print(f"\nVerification for first eigenvector:")
print(f"A @ v = {A @ v1}")
print(f"λ * v = {lambda1 * v1}")

### 9.4 Matrix Norms

**np.linalg.norm()**: Compute matrix or vector norms

**Parameters**:

- `x`: Input array
- `ord`: Order of the norm (default: Frobenius for matrices, 2-norm for vectors)
- `axis`: Axis along which to compute norm


In [ ]:
# Vector norms
v = np.array([3, 4])

# L2 norm (Euclidean)
l2_norm = np.linalg.norm(v)
print(f"Vector: {v}")
print(f"L2 norm: {l2_norm}")  # sqrt(3² + 4²) = 5

# L1 norm (Manhattan)
l1_norm = np.linalg.norm(v, ord=1)
print(f"L1 norm: {l1_norm}")  # |3| + |4| = 7

# Matrix norms
A = np.array([[1, 2],
              [3, 4]])

frobenius = np.linalg.norm(A, 'fro')
print(f"\nMatrix Frobenius norm: {frobenius}")

## 10. Random Number Generation

Critical for initializing neural networks and creating datasets.

**Modern approach**: Use `np.random.default_rng()` (Generator)

```mermaid
graph TD
    A[Random Generation] --> B[Uniform]
    A --> C[Normal/Gaussian]
    A --> D[Integer]
    A --> E[Choice/Shuffle]
    B --> B1[random, uniform]
    C --> C1["normal, standard_normal"]
    D --> D1[integers]
    E --> E1["choice, shuffle"]
```


In [ ]:
# Create random number generator with seed for reproducibility
rng = np.random.default_rng(seed=42)

# Random floats in [0, 1)
random_floats = rng.random((3, 4))
print("Random floats [0, 1):")
print(random_floats)

# Random integers
# integers(low, high, size) - generates integers in [low, high)
random_ints = rng.integers(0, 10, size=(2, 5))
print("\nRandom integers [0, 10):")
print(random_ints)

### 10.1 Normal (Gaussian) Distribution

**rng.normal(loc, scale, size)**: Normal distribution

**Parameters**:

- `loc`: Mean (μ) - default 0
- `scale`: Standard deviation (σ) - default 1
- `size`: Output shape

**rng.standard_normal(size)**: Standard normal (μ=0, σ=1)


In [ ]:
rng = np.random.default_rng(42)

# Standard normal (mean=0, std=1)
std_normal = rng.standard_normal((3, 4))
print("Standard normal (μ=0, σ=1):")
print(std_normal)
print(f"Mean: {std_normal.mean():.4f}, Std: {std_normal.std():.4f}")

# Custom normal (mean=10, std=2)
custom_normal = rng.normal(loc=10, scale=2, size=(3, 4))
print("\nCustom normal (μ=10, σ=2):")
print(custom_normal)
print(f"Mean: {custom_normal.mean():.4f}, Std: {custom_normal.std():.4f}")

### 10.2 Uniform Distribution

**rng.uniform(low, high, size)**: Uniform distribution

**Parameters**:

- `low`: Lower boundary (inclusive) - default 0
- `high`: Upper boundary (exclusive) - default 1
- `size`: Output shape


In [ ]:
rng = np.random.default_rng(42)

# Uniform in [0, 1)
uniform_01 = rng.random((2, 3))
print("Uniform [0, 1):")
print(uniform_01)

# Uniform in [-5, 5)
uniform_custom = rng.uniform(-5, 5, size=(2, 3))
print("\nUniform [-5, 5):")
print(uniform_custom)

### 10.3 Random Choice and Shuffling

**rng.choice(a, size, replace, p)**: Random samples from array

**Parameters**:

- `a`: Array or int (if int, samples from np.arange(a))
- `size`: Output shape (optional)
- `replace`: bool - Sample with replacement (default True)
- `p`: Probabilities for each element (optional)

**rng.shuffle(x)**: Shuffle array in-place


In [ ]:
rng = np.random.default_rng(42)

# Random choice from array
colors = np.array(['red', 'blue', 'green', 'yellow'])
chosen = rng.choice(colors, size=10)
print("Random color choices:")
print(chosen)

# Without replacement
chosen_unique = rng.choice(colors, size=3, replace=False)
print("\nUnique color choices:")
print(chosen_unique)

# Weighted choice
probabilities = [0.1, 0.2, 0.3, 0.4]
weighted = rng.choice(colors, size=100, p=probabilities)
print("\nWeighted choices (100 samples):")
unique, counts = np.unique(weighted, return_counts=True)
for color, count in zip(unique, counts):
    print(f"{color}: {count}")

# Shuffle
arr = np.arange(10)
print(f"\nOriginal: {arr}")
rng.shuffle(arr)
print(f"Shuffled: {arr}")

### 10.4 Reproducibility with Seeds


In [ ]:
# Same seed = same random numbers
rng1 = np.random.default_rng(42)
rng2 = np.random.default_rng(42)

print("RNG 1:", rng1.random(5))
print("RNG 2:", rng2.random(5))

# Different seeds = different random numbers
rng3 = np.random.default_rng(123)
print("\nRNG 3 (different seed):", rng3.random(5))

## 11. Advanced Indexing

Powerful techniques for complex data selection.

```mermaid
graph TD
    A[Advanced Indexing] --> B[Fancy Indexing]
    A --> C[Boolean Masks]
    A --> D[np.where]
    A --> E[np.argmax/argmin]
    B --> B1[Integer arrays as indices]
    C --> C1[Conditional selection]
    D --> D1[Conditional replacement]
    E --> E1[Find extreme values]
```


### 11.1 Fancy Indexing

Use arrays of indices to access multiple elements.


In [ ]:
arr = np.array([10, 20, 30, 40, 50, 60, 70])

# Select specific indices
indices = [0, 2, 5]
selected = arr[indices]
print(f"Array: {arr}")
print(f"Indices {indices}: {selected}")

# 2D fancy indexing
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Select elements at (0,0), (1,1), (2,2)
rows = [0, 1, 2]
cols = [0, 1, 2]
diagonal = arr_2d[rows, cols]
print(f"\nDiagonal elements: {diagonal}")

# Select multiple rows
selected_rows = arr_2d[[0, 2]]  # Rows 0 and 2
print("\nRows 0 and 2:")
print(selected_rows)

### 11.2 np.where()

**Syntax**: `np.where(condition, x, y)`

**Parameters**:

- `condition`: Boolean array
- `x`: Values where condition is True
- `y`: Values where condition is False

**Or**: `np.where(condition)` returns indices where condition is True


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Get indices where condition is True
indices = np.where(arr > 5)
print(f"Array: {arr}")
print(f"Indices where > 5: {indices[0]}")
print(f"Values where > 5: {arr[indices]}")

# Conditional replacement
result = np.where(arr > 5, arr, 0)  # Keep if > 5, else 0
print(f"\nReplace ≤5 with 0: {result}")

# Multiple conditions
result = np.where((arr > 3) & (arr < 8), arr, -1)
print(f"Keep if 3 < x < 8, else -1: {result}")

# Replace odd/even
result = np.where(arr % 2 == 0, 'even', 'odd')
print(f"\nOdd/Even labels: {result}")

### 11.3 np.argmax() and np.argmin()

Find indices of maximum/minimum values.

**Syntax**: `np.argmax(arr, axis=None)`

**Parameters**:

- `arr`: Input array
- `axis`: Axis along which to find max (None for flattened array)


In [ ]:
arr = np.array([3, 7, 2, 9, 1, 5])

# Find index of max/min
max_idx = np.argmax(arr)
min_idx = np.argmin(arr)

print(f"Array: {arr}")
print(f"Max value {arr[max_idx]} at index {max_idx}")
print(f"Min value {arr[min_idx]} at index {min_idx}")

# 2D array - axis operations
arr_2d = np.array([[1, 5, 3],
                   [9, 2, 7],
                   [4, 6, 8]])

print("\n2D Array:")
print(arr_2d)

# Max in each column (axis=0)
max_cols = np.argmax(arr_2d, axis=0)
print(f"\nRow indices of max in each column: {max_cols}")

# Max in each row (axis=1)
max_rows = np.argmax(arr_2d, axis=1)
print(f"Column indices of max in each row: {max_rows}")

### 11.4 np.argsort()

Return indices that would sort the array.

**Syntax**: `np.argsort(arr, axis=-1, kind='quicksort')`


In [ ]:
arr = np.array([3, 1, 4, 1, 5, 9, 2, 6])

# Get sorting indices
sorted_indices = np.argsort(arr)
print(f"Array: {arr}")
print(f"Sorting indices: {sorted_indices}")
print(f"Sorted array: {arr[sorted_indices]}")

# Descending order
desc_indices = np.argsort(arr)[::-1]
print(f"\nDescending: {arr[desc_indices]}")

# Top-3 values
top3_indices = np.argsort(arr)[-3:]
print(f"\nTop-3 indices: {top3_indices}")
print(f"Top-3 values: {arr[top3_indices]}")

## 12. Aggregation and Statistics

Compute statistics across arrays or specific axes.

**⚡ Key Concept**: All aggregation functions support the **`axis` parameter** - this is one of the most important features in NumPy! Understanding how `axis` works is critical for data manipulation and deep learning.

> 📚 **Note**: Section 12.1 contains a detailed, comprehensive explanation of the `axis` parameter with visual diagrams, examples, and common pitfalls. Don't skip it!

```mermaid
graph TD
    A[Statistics] --> B[Basic Stats]
    A --> C[Positional Stats]
    A --> D[Logical Operations]
    B --> B1["sum, mean, std, var"]
    B --> B2["min, max, median"]
    C --> C1["argmin, argmax"]
    D --> D1["all, any"]

    style A fill:#e1f5ff,stroke:#333,stroke-width:2px
```


In [ ]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

print("Array:")
print(arr)
print()

# Global statistics
print(f"Sum: {np.sum(arr)}")
print(f"Mean: {np.mean(arr)}")
print(f"Std deviation: {np.std(arr)}")
print(f"Variance: {np.var(arr)}")
print(f"Min: {np.min(arr)}")
print(f"Max: {np.max(arr)}")
print(f"Median: {np.median(arr)}")

### 12.1 Axis-wise Operations

#### Understanding the `axis` Parameter - The Most Important Concept!

The `axis` parameter is one of the most confusing but crucial concepts in NumPy (and PyTorch). Let's break it down clearly.

**Core Concept**: The `axis` parameter tells NumPy **which dimension to collapse** during an operation.

---

#### The Intuitive Way to Think About Axis

**Key Mental Model**:

> **`axis=N` means "operate ALONG that dimension" or "collapse that dimension"**

For a 2D array with shape `(3, 4)`:

- **axis=0** → Collapse the **first dimension** (rows) → Result has shape `(4,)`
- **axis=1** → Collapse the **second dimension** (columns) → Result has shape `(3,)`
- **axis=None** → Collapse **all dimensions** → Result is a scalar

---

#### Visual Understanding

```
Original 2D Array (3 rows × 4 columns):
┌─────────────────────┐
│  1   2   3   4  ←── row 0
│  5   6   7   8  ←── row 1
│  9  10  11  12  ←── row 2
└─────────────────────┘
  ↑   ↑   ↑   ↑
 col col col col
  0   1   2   3

axis=0: "Collapse rows" → Sum down the columns
        Result: [15, 18, 21, 24]  (shape: 4,)
        ↓
        1+5+9=15, 2+6+10=18, 3+7+11=21, 4+8+12=24

axis=1: "Collapse columns" → Sum across the rows
        Result: [10, 26, 42]  (shape: 3,)
        →
        1+2+3+4=10, 5+6+7+8=26, 9+10+11+12=42
```

---

#### Memory Trick 🧠

**The Disappearing Dimension Rule:**

> The axis you specify **disappears** from the result shape!

- Start with shape: `(3, 4)`
- Use `axis=0`: dimension 0 disappears → `(4,)`
- Use `axis=1`: dimension 1 disappears → `(3,)`
- Use `axis=None`: all dimensions disappear → `()` (scalar)

---

#### Formal Definition

**axis parameter**: Dimension along which operation is performed

- **`axis=0`**: Operate down the rows (column-wise operation)
- **`axis=1`**: Operate across the columns (row-wise operation)
- **`axis=None`**: Operate across entire array (default)

```mermaid
flowchart TB
    subgraph AxisDemo["Axis Operations on 2D Array"]
        A["Array Shape: #40;3, 4#41;<br/>3 rows × 4 columns"] --> B["axis=0<br/>#40;collapse rows#41;"]
        A --> C["axis=1<br/>#40;collapse columns#41;"]
        A --> D["axis=None<br/>#40;collapse all#41;"]
        B --> B1["Result Shape: #40;4,#41;<br/>4 column sums"]
        C --> C1["Result Shape: #40;3,#41;<br/>3 row sums"]
        D --> D1["Result: scalar<br/>1 total sum"]
    end

    style A fill:#e1f5ff,stroke:#333,stroke-width:2px
    style B fill:#ffe6e6,stroke:#333
    style C fill:#e6ffe6,stroke:#333
    style D fill:#fff4e6,stroke:#333
    style B1 fill:#ffcccc,stroke:#333
    style C1 fill:#ccffcc,stroke:#333
    style D1 fill:#ffe6cc,stroke:#333
```


In [ ]:
# Create a clear example array
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

print("="*60)
print("Original Array - Shape: (3, 4)")
print("="*60)
print(arr)
print(f"\nShape: {arr.shape}  →  3 rows × 4 columns")

print("\n" + "="*60)
print("axis=None (default) - Collapse ALL dimensions")
print("="*60)
sum_all = np.sum(arr)
print(f"np.sum(arr, axis=None) = {sum_all}")
print(f"Result shape: () ← scalar")
print(f"Calculation: 1+2+3+4+5+6+7+8+9+10+11+12 = {sum_all}")

print("\n" + "="*60)
print("axis=0 - Collapse ROWS (operate down columns)")
print("="*60)
sum_axis0 = np.sum(arr, axis=0)
print(f"np.sum(arr, axis=0) = {sum_axis0}")
print(f"Result shape: {sum_axis0.shape} ← dimension 0 disappeared!")
print(f"Calculation (column by column):")
print(f"  Column 0: 1+5+9 = {sum_axis0[0]}")
print(f"  Column 1: 2+6+10 = {sum_axis0[1]}")
print(f"  Column 2: 3+7+11 = {sum_axis0[2]}")
print(f"  Column 3: 4+8+12 = {sum_axis0[3]}")

print("\n" + "="*60)
print("axis=1 - Collapse COLUMNS (operate across rows)")
print("="*60)
sum_axis1 = np.sum(arr, axis=1)
print(f"np.sum(arr, axis=1) = {sum_axis1}")
print(f"Result shape: {sum_axis1.shape} ← dimension 1 disappeared!")
print(f"Calculation (row by row):")
print(f"  Row 0: 1+2+3+4 = {sum_axis1[0]}")
print(f"  Row 1: 5+6+7+8 = {sum_axis1[1]}")
print(f"  Row 2: 9+10+11+12 = {sum_axis1[2]}")

In [ ]:
# More operations with axis parameter
print("="*60)
print("Different Operations with axis Parameter")
print("="*60)

arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

print("\nOriginal array:")
print(arr)
print()

# Mean
print("MEAN (average):")
print(f"  axis=0 (column means): {np.mean(arr, axis=0)}")
print(f"  axis=1 (row means):    {np.mean(arr, axis=1)}")

# Max
print("\nMAX (maximum):")
print(f"  axis=0 (max per column): {np.max(arr, axis=0)}")
print(f"  axis=1 (max per row):    {np.max(arr, axis=1)}")

# Min
print("\nMIN (minimum):")
print(f"  axis=0 (min per column): {np.min(arr, axis=0)}")
print(f"  axis=1 (min per row):    {np.min(arr, axis=1)}")

# Standard deviation
print("\nSTD (standard deviation):")
print(f"  axis=0 (std per column): {np.std(arr, axis=0)}")
print(f"  axis=1 (std per row):    {np.std(arr, axis=1)}")

# Argmax (index of maximum)
print("\nARGMAX (index of maximum value):")
print(f"  axis=0 (row index of max per column): {np.argmax(arr, axis=0)}")
print(f"  axis=1 (col index of max per row):    {np.argmax(arr, axis=1)}")

print("\n" + "="*60)
print("Key Pattern: ALL aggregation functions support axis!")
print("="*60)

#### Understanding axis with 3D Arrays (Critical for Deep Learning!)

3D arrays are common in deep learning (e.g., batches of images, sequences). Understanding axis here is crucial!

**3D Array Structure:**

- **axis=0**: Batch dimension (which sample)
- **axis=1**: Height dimension (or sequence length)
- **axis=2**: Width dimension (or feature dimension)

**The Disappearing Dimension Rule Still Applies!**

```
3D Array shape: (2, 3, 4)
                 ↓  ↓  ↓
            axis=0  1  2

axis=0 → shape (3, 4)  ← first dimension gone
axis=1 → shape (2, 4)  ← second dimension gone
axis=2 → shape (2, 3)  ← third dimension gone
```

**Visual Representation:**

```mermaid
flowchart TB
    subgraph ThreeD["3D Array: Shape #40;2, 3, 4#41;"]
        A["2 matrices<br/>3 rows each<br/>4 columns each"]
    end

    ThreeD --> B["axis=0<br/>Collapse matrices"]
    ThreeD --> C["axis=1<br/>Collapse rows"]
    ThreeD --> D["axis=2<br/>Collapse columns"]

    B --> B1["Result: #40;3, 4#41;<br/>Average across<br/>2 matrices"]
    C --> C1["Result: #40;2, 4#41;<br/>Average across<br/>3 rows"]
    D --> D1["Result: #40;2, 3#41;<br/>Average across<br/>4 columns"]

    style A fill:#e1f5ff,stroke:#333,stroke-width:2px
    style B fill:#ffe6e6,stroke:#333
    style C fill:#e6ffe6,stroke:#333
    style D fill:#fff4e6,stroke:#333
```


In [ ]:
# 3D Array Example
print("="*60)
print("3D Array - axis Parameter Examples")
print("="*60)

# Create a 3D array: 2 matrices, each 3×4
arr_3d = np.array([
    [[1, 2, 3, 4],
     [5, 6, 7, 8],
     [9, 10, 11, 12]],
    
    [[13, 14, 15, 16],
     [17, 18, 19, 20],
     [21, 22, 23, 24]]
])

print(f"\nOriginal 3D array shape: {arr_3d.shape}")
print(f"Interpretation: 2 matrices, each 3 rows × 4 columns")
print(f"\nMatrix 0:")
print(arr_3d[0])
print(f"\nMatrix 1:")
print(arr_3d[1])

print("\n" + "="*60)
print("Summing along different axes:")
print("="*60)

# axis=0: Collapse the first dimension (sum across matrices)
sum_axis0 = np.sum(arr_3d, axis=0)
print(f"\naxis=0 (sum across matrices):")
print(f"Result shape: {sum_axis0.shape}  ← axis 0 disappeared!")
print(f"Result:")
print(sum_axis0)
print(f"Each value is the sum of corresponding positions across 2 matrices")
print(f"Example: top-left = {arr_3d[0,0,0]} + {arr_3d[1,0,0]} = {sum_axis0[0,0]}")

# axis=1: Collapse the second dimension (sum down rows in each matrix)
sum_axis1 = np.sum(arr_3d, axis=1)
print(f"\naxis=1 (sum down rows in each matrix):")
print(f"Result shape: {sum_axis1.shape}  ← axis 1 disappeared!")
print(f"Result:")
print(sum_axis1)
print(f"Each row is summed within each matrix")

# axis=2: Collapse the third dimension (sum across columns in each matrix)
sum_axis2 = np.sum(arr_3d, axis=2)
print(f"\naxis=2 (sum across columns in each matrix):")
print(f"Result shape: {sum_axis2.shape}  ← axis 2 disappeared!")
print(f"Result:")
print(sum_axis2)
print(f"Each column is summed within each matrix")

# Multiple axes
sum_axis01 = np.sum(arr_3d, axis=(0, 1))
print(f"\naxis=(0,1) (sum across matrices AND rows):")
print(f"Result shape: {sum_axis01.shape}  ← axes 0 and 1 disappeared!")
print(f"Result: {sum_axis01}")
print(f"Only columns remain - we summed everything else!")

#### Common Mistakes and How to Avoid Them ⚠️

**Mistake #1: Confusing "row" vs "column" operations**

```python
# Common confusion:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# ❌ WRONG thinking: "axis=0 means rows"
# ✅ CORRECT thinking: "axis=0 collapses the row dimension"

np.sum(arr, axis=0)  # → [5, 7, 9]  (summed DOWN the rows)
```

**Mistake #2: Forgetting the disappearing dimension rule**

```python
arr.shape = (3, 4)

# Use axis=0
result = np.sum(arr, axis=0)
# Expected shape: (4,)  ← NOT (3, 4)!
```

**Mistake #3: Wrong axis for the desired operation**

```python
# If you want to sum each row:
# ✅ CORRECT: axis=1 (collapse columns)
row_sums = np.sum(arr, axis=1)

# ❌ WRONG: axis=0 (this gives column sums)
row_sums = np.sum(arr, axis=0)  # This is wrong!
```

---

#### Quick Reference Guide 📋

**2D Array Operations:**

| Goal            | axis value  | Result                          |
| --------------- | ----------- | ------------------------------- |
| Sum each column | `axis=0`    | Array with length = num_columns |
| Sum each row    | `axis=1`    | Array with length = num_rows    |
| Sum everything  | `axis=None` | Single number (scalar)          |

**Shape Transformation:**

| Original Shape | axis         | Result Shape |
| -------------- | ------------ | ------------ |
| `(3, 4)`       | `axis=0`     | `(4,)`       |
| `(3, 4)`       | `axis=1`     | `(3,)`       |
| `(2, 3, 4)`    | `axis=0`     | `(3, 4)`     |
| `(2, 3, 4)`    | `axis=1`     | `(2, 4)`     |
| `(2, 3, 4)`    | `axis=2`     | `(2, 3)`     |
| `(2, 3, 4)`    | `axis=(0,2)` | `(3,)`       |

**Functions that support axis parameter:**

- Aggregations: `sum`, `mean`, `std`, `var`, `min`, `max`, `median`
- Positional: `argmin`, `argmax`, `argwhere`
- Logical: `all`, `any`
- Cumulative: `cumsum`, `cumprod`
- And many more!

---

#### Pro Tips 💡

1. **Always check the result shape** to verify you used the correct axis
2. **Remember**: The axis you specify is the one that **disappears**
3. **Use keepdims=True** if you want to preserve the dimension (as size 1):
   ```python
   arr = np.array([[1, 2, 3], [4, 5, 6]])
   result = np.sum(arr, axis=1, keepdims=True)
   # Shape: (2, 1) instead of (2,)
   ```
4. **For PyTorch**: axis is called `dim` (dimension), but works the same way!


In [ ]:
# Demonstrating keepdims parameter
print("="*60)
print("Using keepdims=True to preserve dimensions")
print("="*60)

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print(f"\nOriginal array shape: {arr.shape}")
print(arr)

# Without keepdims (default)
sum_without = np.sum(arr, axis=1)
print(f"\naxis=1, keepdims=False (default):")
print(f"Result: {sum_without}")
print(f"Shape: {sum_without.shape}  ← 1D array")

# With keepdims
sum_with = np.sum(arr, axis=1, keepdims=True)
print(f"\naxis=1, keepdims=True:")
print(f"Result:\n{sum_with}")
print(f"Shape: {sum_with.shape}  ← 2D array (dimension preserved as size 1)")

print("\n" + "="*60)
print("Why use keepdims? For broadcasting!")
print("="*60)

# Normalize each row by its sum
normalized = arr / sum_with  # Broadcasting works!
print(f"\nNormalize each row (divide by row sum):")
print(f"arr / sum_with:")
print(normalized)
print(f"\nEach row now sums to 1.0:")
print(f"Row sums: {np.sum(normalized, axis=1)}")

print("\n" + "="*60)
print("Practical Example: Mean Centering")
print("="*60)

data = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])

print("Original data:")
print(data)

# Center each column (subtract column mean)
col_means = np.mean(data, axis=0, keepdims=True)
print(f"\nColumn means (keepdims=True): shape {col_means.shape}")
print(col_means)

centered = data - col_means
print("\nCentered data (each column mean is now 0):")
print(centered)
print(f"\nVerify - column means are ~0:")
print(np.mean(centered, axis=0))

#### Visual Summary: The Complete Picture

```mermaid
flowchart TB
    subgraph Concept["Core Concept"]
        A["axis Parameter<br/>Specifies which dimension to COLLAPSE"]
    end

    subgraph TwoD["2D Array #40;3, 4#41;"]
        B1["axis=0<br/>#40;collapse rows#41;"] --> B2["Shape: #40;4,#41;<br/>4 column results"]
        C1["axis=1<br/>#40;collapse columns#41;"] --> C2["Shape: #40;3,#41;<br/>3 row results"]
        D1["axis=None<br/>#40;collapse all#41;"] --> D2["Shape: #40;#41;<br/>1 scalar result"]
    end

    subgraph ThreeD["3D Array #40;2, 3, 4#41;"]
        E1["axis=0"] --> E2["#40;3, 4#41;"]
        F1["axis=1"] --> F2["#40;2, 4#41;"]
        G1["axis=2"] --> G2["#40;2, 3#41;"]
        H1["axis=#40;0,1#41;"] --> H2["#40;4,#41;"]
    end

    subgraph Rules["Golden Rules"]
        R1["✓ Specified axis DISAPPEARS from result"]
        R2["✓ Use keepdims=True to preserve as size 1"]
        R3["✓ In PyTorch: axis → dim"]
        R4["✓ Check result shape to verify!"]
    end

    Concept --> TwoD
    Concept --> ThreeD
    TwoD --> Rules
    ThreeD --> Rules

    style Concept fill:#e1f5ff,stroke:#333,stroke-width:3px
    style B2 fill:#ffcccc,stroke:#333
    style C2 fill:#ccffcc,stroke:#333
    style D2 fill:#ffe6cc,stroke:#333
    style E2 fill:#e6ccff,stroke:#333
    style F2 fill:#cce6ff,stroke:#333
    style G2 fill:#ffccf2,stroke:#333
    style H2 fill:#ffffcc,stroke:#333
    style Rules fill:#f0f0f0,stroke:#333,stroke-width:2px
```

---

#### Summary Table: axis Parameter at a Glance

| Aspect                 | Description                                    | Example                   |
| ---------------------- | ---------------------------------------------- | ------------------------- |
| **Purpose**            | Specify dimension to collapse during operation | `np.sum(arr, axis=0)`     |
| **Effect**             | The specified dimension disappears from result | `(3,4)` → axis=0 → `(4,)` |
| **2D: axis=0**         | Operate down rows (column-wise)                | Sum each column           |
| **2D: axis=1**         | Operate across columns (row-wise)              | Sum each row              |
| **axis=None**          | Operate on flattened array (all elements)      | Total sum                 |
| **Multiple axes**      | Collapse multiple dimensions                   | `axis=(0,1)`              |
| **keepdims**           | Keep dimension as size 1                       | `keepdims=True`           |
| **PyTorch equivalent** | Same concept, different name                   | `dim` instead of `axis`   |

**Remember:**

> 🎯 The axis you specify is the dimension that **disappears** from your result!  
> 🔍 Always verify by checking the result shape!  
> 🚀 This knowledge transfers directly to PyTorch with `dim` parameter!


### 12.2 Cumulative Operations

**np.cumsum()**: Cumulative sum
**np.cumprod()**: Cumulative product


In [ ]:
arr = np.array([1, 2, 3, 4, 5])

print(f"Array: {arr}")
print(f"Cumulative sum: {np.cumsum(arr)}")
print(f"Cumulative product: {np.cumprod(arr)}")

# 2D cumulative sum
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6]])
print("\n2D Array:")
print(arr_2d)
print("\nCumulative sum (flattened):")
print(np.cumsum(arr_2d))
print("\nCumulative sum along columns (axis=0):")
print(np.cumsum(arr_2d, axis=0))

### 12.3 Logical Operations

**np.all()**: Returns True if all elements are True
**np.any()**: Returns True if any element is True


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])

print(f"Array: {arr}")
print(f"All elements > 0: {np.all(arr > 0)}")
print(f"All elements > 3: {np.all(arr > 3)}")
print(f"Any element > 5: {np.any(arr > 5)}")
print(f"Any element > 10: {np.any(arr > 10)}")

# With 2D array
arr_2d = np.array([[True, True, False],
                   [True, False, False]])

print("\nBoolean array:")
print(arr_2d)
print(f"\nAll True in each row: {np.all(arr_2d, axis=1)}")
print(f"Any True in each column: {np.any(arr_2d, axis=0)}")

## 13. Stacking and Concatenation

Combine multiple arrays into larger arrays.

```mermaid
graph TD
    A[Array Combining] --> B[Concatenation]
    A --> C[Stacking]
    B --> B1["np.concatenate"]
    C --> C1["np.vstack (vertical)"]
    C --> C2["np.hstack (horizontal)"]
    C --> C3["np.stack (new axis)"]
```


### 13.1 np.concatenate()

**Syntax**: `np.concatenate((arr1, arr2, ...), axis=0)`

**Parameters**:

- `arrays`: Tuple of arrays to concatenate
- `axis`: Axis along which to concatenate (default 0)


In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# 1D concatenation
result = np.concatenate((a, b))
print("1D concatenation:")
print(f"{a} + {b} = {result}")

# 2D concatenation
a_2d = np.array([[1, 2], [3, 4]])
b_2d = np.array([[5, 6], [7, 8]])

# Concatenate along axis 0 (stack vertically)
result_v = np.concatenate((a_2d, b_2d), axis=0)
print("\nVertical concatenation (axis=0):")
print(result_v)

# Concatenate along axis 1 (stack horizontally)
result_h = np.concatenate((a_2d, b_2d), axis=1)
print("\nHorizontal concatenation (axis=1):")
print(result_h)

### 13.2 np.vstack() and np.hstack()

**np.vstack()**: Stack arrays vertically (row-wise)
**np.hstack()**: Stack arrays horizontally (column-wise)


In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Vertical stack (creates 2D array)
v_stacked = np.vstack((a, b))
print("vstack (vertical):")
print(v_stacked)
print(f"Shape: {v_stacked.shape}")

# Horizontal stack
h_stacked = np.hstack((a, b))
print("\nhstack (horizontal):")
print(h_stacked)
print(f"Shape: {h_stacked.shape}")

# 2D examples
a_2d = np.array([[1, 2], [3, 4]])
b_2d = np.array([[5, 6], [7, 8]])

print("\nOriginal arrays:")
print("a_2d:")
print(a_2d)
print("b_2d:")
print(b_2d)

print("\nvstack:")
print(np.vstack((a_2d, b_2d)))

print("\nhstack:")
print(np.hstack((a_2d, b_2d)))

### 13.3 np.stack()

Join arrays along a new axis.

**Syntax**: `np.stack((arr1, arr2, ...), axis=0)`

**Parameters**:

- `arrays`: Sequence of arrays (must have same shape)
- `axis`: Axis in result array along which input arrays are stacked


In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Stack along new axis 0
stacked_0 = np.stack((a, b), axis=0)
print("stack along axis=0:")
print(stacked_0)
print(f"Shape: {stacked_0.shape}")

# Stack along new axis 1
stacked_1 = np.stack((a, b), axis=1)
print("\nstack along axis=1:")
print(stacked_1)
print(f"Shape: {stacked_1.shape}")

# Compare with vstack and hstack
print("\nComparison:")
print(f"np.vstack: same as stack(axis=0)")
print(f"np.hstack: concatenates, doesn't add new axis")

### 13.4 np.split()

Split array into multiple sub-arrays.

**Syntax**: `np.split(arr, indices_or_sections, axis=0)`

**Parameters**:

- `arr`: Array to split
- `indices_or_sections`: int or 1D array
  - If int: Split into N equal arrays
  - If array: Split at specified indices
- `axis`: Axis along which to split


In [ ]:
arr = np.arange(12)
print(f"Original array: {arr}")

# Split into 3 equal parts
parts = np.split(arr, 3)
print("\nSplit into 3 parts:")
for i, part in enumerate(parts):
    print(f"Part {i}: {part}")

# Split at specific indices
parts = np.split(arr, [3, 7])  # Split at index 3 and 7
print("\nSplit at indices [3, 7]:")
for i, part in enumerate(parts):
    print(f"Part {i}: {part}")

# 2D split
arr_2d = np.arange(12).reshape(3, 4)
print("\n2D array (3×4):")
print(arr_2d)

# Split rows
rows = np.split(arr_2d, 3, axis=0)
print("\nSplit into 3 rows:")
for i, row in enumerate(rows):
    print(f"Row {i}:\n{row}")

## 14. NumPy to PyTorch Bridge

Understanding the transition from NumPy to PyTorch.

```mermaid
flowchart LR
    A[NumPy Array] -->|torch.from_numpy| B[PyTorch Tensor]
    B -->|.numpy| A
    C[Python List] -->|torch.tensor| B
    D[NumPy Operations] -.->|Similar API| E[PyTorch Operations]
    style A fill:#f9f,stroke:#333
    style B fill:#9ff,stroke:#333
```


### 14.1 Key Similarities

| Concept             | NumPy                | PyTorch                   |
| ------------------- | -------------------- | ------------------------- |
| **Main object**     | `ndarray`            | `Tensor`                  |
| **Shape**           | `.shape`             | `.shape`                  |
| **Reshape**         | `.reshape()`         | `.reshape()` or `.view()` |
| **Transpose**       | `.T`                 | `.T`                      |
| **Matrix multiply** | `@` or `np.matmul()` | `@` or `torch.matmul()`   |
| **Element-wise**    | `+, -, *, /`         | `+, -, *, /`              |
| **Broadcasting**    | ✓                    | ✓                         |
| **Indexing**        | `arr[i, j]`          | `tensor[i, j]`            |
| **Random**          | `np.random.*`        | `torch.rand*`             |
| **GPU support**     | ✗                    | ✓ (`.cuda()`)             |
| **Autograd**        | ✗                    | ✓ (`.backward()`)         |


### 14.2 Common Patterns in Both

Here are NumPy examples that translate directly to PyTorch:


In [ ]:
# NumPy patterns that work similarly in PyTorch

# 1. Creating tensors/arrays
np_zeros = np.zeros((3, 4))
np_ones = np.ones((2, 3))
np_rand = np.random.randn(2, 2)
print("NumPy zeros:")
print(np_zeros)

# PyTorch equivalent:
# torch_zeros = torch.zeros(3, 4)
# torch_ones = torch.ones(2, 3)
# torch_rand = torch.randn(2, 2)

# 2. Reshaping
arr = np.arange(12)
reshaped = arr.reshape(3, 4)
print("\nNumPy reshape:")
print(reshaped)

# PyTorch equivalent:
# tensor = torch.arange(12)
# reshaped = tensor.reshape(3, 4)  # or tensor.view(3, 4)

# 3. Broadcasting
matrix = np.ones((3, 4))
vector = np.array([1, 2, 3, 4])
result = matrix + vector
print("\nNumPy broadcasting result shape:", result.shape)

# PyTorch: exact same broadcasting rules!

# 4. Indexing and slicing
arr = np.arange(20).reshape(4, 5)
print("\nNumPy slicing arr[:2, 1:4]:")
print(arr[:2, 1:4])

# PyTorch: identical syntax!
# tensor[:2, 1:4]

### 14.3 Practical Example: Image Processing

Image data workflow (common in deep learning):

```mermaid
flowchart LR
    A["Image File"] --> B["NumPy Array\n(H, W, C)"]
    B --> C["Normalize\n/ 255.0"]
    C --> D["Transpose\n(C, H, W)"]
    D --> E["PyTorch Tensor"]
    E --> F["Add Batch Dim\n(1, C, H, W)"]
    F --> G[Neural Network]
```


In [ ]:
# Simulating image processing pipeline
rng = np.random.default_rng(42)

# Simulate RGB image: Height=32, Width=32, Channels=3
image = rng.integers(0, 256, size=(32, 32, 3), dtype=np.uint8)
print(f"Original image shape: {image.shape}")  # (H, W, C)
print(f"Data type: {image.dtype}")
print(f"Value range: [{image.min()}, {image.max()}]")

# Step 1: Normalize to [0, 1]
normalized = image.astype(np.float32) / 255.0
print(f"\nNormalized range: [{normalized.min():.2f}, {normalized.max():.2f}]")

# Step 2: Transpose to (C, H, W) - PyTorch format
transposed = normalized.transpose(2, 0, 1)
print(f"Transposed shape: {transposed.shape}")  # (C, H, W)

# Step 3: Add batch dimension
batched = np.expand_dims(transposed, axis=0)
print(f"With batch dimension: {batched.shape}")  # (1, C, H, W)

# In PyTorch, you'd convert at this point:
# tensor = torch.from_numpy(batched)
# output = model(tensor)

print("\nThis array is now ready for PyTorch!")

### 14.4 Batch Processing Example

Understanding batches (crucial for deep learning):


In [ ]:
# Create a batch of samples
# Common scenario: 64 samples, each is a 28×28 image with 1 channel

batch_size = 64
channels = 1
height = 28
width = 28

# Create batch (normally loaded from dataset)
rng = np.random.default_rng(42)
batch = rng.random((batch_size, channels, height, width), dtype=np.float32)

print(f"Batch shape: {batch.shape}")  # (N, C, H, W)
print(f"N = batch size: {batch.shape[0]}")
print(f"C = channels: {batch.shape[1]}")
print(f"H = height: {batch.shape[2]}")
print(f"W = width: {batch.shape[3]}")

# Access individual samples
first_sample = batch[0]  # Shape: (1, 28, 28)
print(f"\nFirst sample shape: {first_sample.shape}")

# Process batch: normalize each sample
mean = batch.mean(axis=(2, 3), keepdims=True)  # Per-sample mean
std = batch.std(axis=(2, 3), keepdims=True)    # Per-sample std
normalized_batch = (batch - mean) / (std + 1e-8)

print(f"\nNormalized batch - mean: {normalized_batch.mean():.2e}")
print(f"Normalized batch - std: {normalized_batch.std():.2f}")

### 14.5 Key Takeaways for PyTorch

**Concepts that transfer directly**:

1. ✅ **Shape manipulation**: `reshape`, `transpose`, `expand_dims`
2. ✅ **Broadcasting rules**: Identical in PyTorch
3. ✅ **Indexing/slicing**: Same syntax
4. ✅ **Mathematical operations**: Element-wise, matrix operations
5. ✅ **Aggregations**: `sum`, `mean`, `max`, etc. with `axis`/`dim`

**New in PyTorch**:

1. 🆕 **GPU acceleration**: `.to('cuda')` or `.cuda()`
2. 🆕 **Automatic differentiation**: `.backward()` for gradients
3. 🆕 **Neural network modules**: `nn.Module`, layers, optimizers
4. 🆕 **Data loaders**: `DataLoader` for batching

**Terminology changes**:

- NumPy: `axis` → PyTorch: `dim` (dimension)
- NumPy: `ndarray` → PyTorch: `Tensor`
- NumPy: `.reshape()` → PyTorch: `.reshape()` or `.view()`


## Summary and Next Steps

### What You've Learned

1. **NumPy Fundamentals**
   - ndarray creation and attributes
   - Data types and memory efficiency

2. **Array Operations**
   - Indexing, slicing, and fancy indexing
   - Reshaping and transposition
   - Views vs copies

3. **Broadcasting**
   - How arrays of different shapes interact
   - Broadcasting rules and applications

4. **Mathematical Operations**
   - Element-wise operations
   - Linear algebra (matrix multiplication, eigenvalues)
   - Aggregations and statistics

5. **Advanced Techniques**
   - Boolean indexing and filtering
   - Random number generation
   - Array stacking and splitting

6. **PyTorch Preparation**
   - Similarities between NumPy and PyTorch
   - Batch processing concepts
   - Data preprocessing workflows

### Practice Exercises

Try these to solidify your understanding:

1. Create a 5×5 matrix with values 1-25, then extract the border elements
2. Implement matrix multiplication from scratch using only element-wise operations
3. Normalize a random array to have mean=0 and std=1
4. Create a function to apply min-max scaling to any array
5. Simulate a simple neural network forward pass using matrix multiplication

### Ready for PyTorch!

You now have a solid foundation in NumPy. When you start PyTorch:

- The syntax will feel familiar
- Broadcasting rules are the same
- Shape manipulation transfers directly
- You'll just add GPU support and automatic differentiation!

```mermaid
graph LR
    A[NumPy Mastery] --> B[PyTorch Basics]
    B --> C[Neural Networks]
    C --> D[Deep Learning]
    style A fill:#9f9,stroke:#333,stroke-width:3px
```

**Happy learning! 🚀**
